# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

anylyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    use_build_context_synchronously: false
    avoid_redundant_argument_values: false
    file_names: false
    only_throw_errors: false
    sort_pub_dependencies: false
    cascade_invocations: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false

