name: subrisu
description: An app to manage subscriptions.

publish_to: 'none' 

version: 2.3.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  app_settings: ^5.1.1
  app_tracking_transparency: ^2.0.3
  cloud_firestore: ^4.9.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  firebase_analytics: ^10.5.1
  firebase_app_check: ^0.1.4
  firebase_auth: ^4.10.0
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_messaging: ^14.6.0
  firebase_remote_config: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.4.7
  flutter_screenutil: ^5.5.4
  freezed_annotation: ^2.2.0
  freezed: ^2.3.3
  get_it: ^7.2.0
  google_mobile_ads: ^3.1.0
  in_app_review: ^2.0.6
  intl: any
  json_serializable: ^6.5.4
  keyboard_actions: ^4.2.0
  package_info_plus: ^4.2.0
  pedantic_mono: ^1.20.1
  pull_down_button: ^0.9.3
  purchases_flutter: ^8.8.0
  riverpod_annotation: ^2.3.1
  riverpod_generator: ^2.1.5
  share_plus: ^7.2.1
  shared_preferences: ^2.0.15
  timezone: ^0.9.0
  url_launcher: ^6.3.1
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen_runner: ^5.2.0
  build_runner: ^2.3.2

flutter_icons:       
  ios: true
  image_path: 'images/app_icon.png'

flutter_native_splash:
  image: 'images/splash.png'
  color: '#ffffff'

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - images/subscription/
