name: subrisu
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  app_settings: ^4.2.0
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  firebase_remote_config: ^2.0.20
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.5.4
  freezed_annotation: ^2.2.0
  freezed: ^2.2.0
  get_it: ^7.2.0
  google_mobile_ads: ^2.2.0
  google_sign_in: ^5.4.2
  in_app_review: ^2.0.6
  intl: ^0.17.0
  json_serializable: ^6.5.4
  package_info_plus: ^3.0.1
  pedantic_mono: ^1.20.1
  purchases_flutter: ^4.9.1
  share_plus: ^6.0.1
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.1.0
  timezone: ^0.9.0
  url_launcher: ^6.1.7
  version: ^3.0.2
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen_runner: ^5.2.0
  build_runner: ^2.3.2

flutter_icons:       
  ios: true
  image_path: 'images/app_icon.png'

flutter_native_splash:
  image: 'images/splash.png'
  color: '#ffffff'

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/subscription/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
